// <auto-generated />
namespace WebApplication27.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Return_shipments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Return_shipments));
        
        string IMigrationMetadata.Id
        {
            get { return "202505310054211_Return_shipments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
